### ISSUE TITLE
Songs with Double quotes does not get displayed

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [PsykoSoldi3r/vscode-itunes#13]
**Description**

Songs like "Heroes" by David Bowie does not get displayed. Next song is displayed instantly when skipping to a song with to double quote

**macOS version**

v10.13.6

**vscode Version**

v1.29.1

**Comment by joeykamsteeg** [comment]
I have released a new version (v0.9.1) to the marketplace of visual studio code.

Thanks for your support! 😊

**Comment by tiagomsmagalhaes** [comment]
Same thing happens with songs with commas such as "Please, Please, Please Let Me What I Want" by The Smiths

**Comment by joeykamsteeg** [comment]
Fixed and will be available on version 0.10.0
