### ISSUE TITLE
No control display

### ISSUE THREAD

**Issue by johnschult** [PsykoSoldi3r/vscode-itunes#18]
**Description**

There is nothing displayed in the status bar except a single icon for mute:

<img width="192" alt="Screen Shot 2019-06-14 at 12 20 47 PM" src="https://user-images.githubusercontent.com/9453/59523296-eb968d00-8e9e-11e9-870e-c7cab7ae84a7.png">

**macOS version**

v10.14.3

**vscode Version**

v1.35.1

**Comment by johnschult** [comment]
And then, after a couple restarts...  it just started working. Your call on this one, close if you want.

**Comment by joeykamsteeg** [comment]
I will close the issue

**Comment by joeykamsteeg** [comment]
I have reproduce this issue, it happend when the song could not displayed correctly and will be fixed in issue #13
