### ISSUE TITLE
Love and Dislike buttons

### ISSUE THREAD

**Issue by anhari** [PsykoSoldi3r/vscode-itunes#19]
**Description**

What do you think of adding love and dislike buttons?

I think we'd be able to leverage something like:

```
# Love
set loved of current track to true

# Dislike
set disliked of current track to true
next track
```

**macOS version**

v10.14.6

**vscode Version**

v1.36.1

**Comment by joeykamsteeg** [comment]
Release on Visual Studio Code Marketplace with version 0.14.0
