### ISSUE TITLE
Apple Music support - Catalina

### ISSUE THREAD

**Issue by ghost** [PsykoSoldi3r/vscode-itunes#21]
With the upcoming Catalina GM release (should be today), we should be expecting the Catalina full release to drop within the next few weeks. (generally a week after the GM release with Apple)

iTunes isn't in Catalina as its functionality has been split up and the music part is now in the aptly named Music.app

I've noticed the extension doesn't currently support the Music.app transition that will come with the release of Catalina. Do you have any plans to update?

**macOS version**
10.15

**vscode Version**
v1.38.1

**Comment by joeykamsteeg** [comment]
I have planned to release soon a updated with support for Catalina. Have updated today my own system.

**Comment by joeykamsteeg** [comment]
Have published a new version (v0.11.0) to marketplace with support for Apple Music
