### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [PsykoSoldi3r/vscode-itunes#6]
Error occured: Error: /Users/user/.vscode/extensions/psykosoldi3r.itunes-vscode-0.8.2/scripts/currentTrack.applescript:131:137: execution error: iTunes devolveu o erro: Sem resposta de AppleEvent. (-1712)

Unfortunately I still don't know how it happens.
macOS 10.13.6
vs code 1.25.1 (1.25.1)

**Comment by joeykamsteeg** [comment]
Thanks for reporting this issue! I will fix this soon as possible. It seems that the extension still should work normally, only the error message is popping up.

**Comment by tiagomsmagalhaes** [comment]
Got another one 

Error occured: Error: /Users/user/.vscode/extensions/psykosoldi3r.itunes-vscode-0.8.2/scripts/currentTrack.applescript:131:137: execution error: iTunes devolveu o erro: A aplicação não está em execução. (-600)

**Comment by joeykamsteeg** [comment]
Self I get this one

/Users/joeykamsteeg/.vscode/extensions/psykosoldi3r.itunes-vscode-0.8.2/scripts/currentTrack.applescript:131:137: execution error: iTunes got an error: AppleEvent timed out. (-1712)

**Comment by joeykamsteeg** [comment]
Have published a new version to Visual Studio Code Marketplace with a fix for this issue ( v0.8.3 )
